server:
  port: 8009

eureka:
  instance:
    hostname: eureka8009.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka8001.com:8001/eureka/