server:
  port: 8001

eureka:
  instance:
    hostname: eureka8001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka8009.com:8009/eureka/